language: node_js
node_js:
  - 10
env:
  matrix:
    secure: mvCjr8recnJME3AsGWP4dq0+tlLNgOyX44XsC+bBq19e7bFHuxMZyQyvBi4ih+J8yB0YU5G3IzO9fcZT/0XyKu6t/QEk44YiiPgTPe3lZuwQF0Ze3hjzn3YhJHFg57tMeNhGTeomEaV8rY4auhcPrLvZfIU5v0Bkdq+wozCDSm/kiKtjJwQwabb+zn3Vt/QaXAP7DSBWgmaHfMHTKwOij6TZKO86tdoEXO0bUwi8PIygum9EKl8RrVAors33A1AOMYKN0jRDfW2qystCP20VjvsRq+QdFFNn3F8MN/tLJ0eOm2bp+xUG574K6hxdvJiccFK26B3Xx5MwGB8qwfwS08YvPAp0iXjAzXKM4bIe/H45CfQ2gESQ2GIXr/gOzduwUF21LZIiOaY14TPlUPiXyoXJtHuTEZeEpB4k77WctLJ59kk4Mfq7MaMAfHKoOa3dez8y+XVcszA/gQ036HtiwrK1K9H8JU7ROrvH014rvxXp16v9WrOuVNnpu978Zj+GeGf7HaKR0CBBG+VmrT9jY6SGdc2ionhtrFmyR+1qSWrFwgv+EbvTDPLMt/hzQ2R8yOGKskj/Mh+DSQ9Bsny4LpG15tsRnIwxN1Zpj/Tjtez47Il8JYxmE9e9+gu7MwfuJuTd3bQgOyfMBMqZ9xd6mw9qZ2ZQN9SaDp9CwFOears=
